name: Demo publish NuGet package

on:
  push:
    branches:
      - nuget

jobs:
  publish:
    name: Demo publish NuGet package
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8

      - name: Login NuGet registry
        run: dotnet nuget add source --username hadonis-testing --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/hadonis-testing/index.json"

      - name: Build and publish NuGet package
        working-directory: ${{ github.workspace }}/nuget/HAdonisTesting
        run: |
          dotnet pack -c Release
          dotnet nuget push "bin/Release/*.nupkg" --source "github"
